# .github/workflows/archive-pages.yml (版本 3 - 修正版)

name: '云端归档页面 (Run spn.sh)'

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: '要归档的目标 URL'
        required: true
        type: string
      spn_args:
        description: 'spn.sh 的其他参数 (例如 -n -w 7 -o ".*")'
        required: false
        default: ''
        type: string

jobs:
  archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Setup spn.sh
        run: |
          curl -L -o spn.sh https://raw.githubusercontent.com/overcast07/wayback-machine-spn-scripts/main/spn.sh
          chmod +x spn.sh

      # 核心步骤：运行脚本
      - name: Run Archive Script
        id: spn_run
        env:
          SPN_API_KEY: ${{ secrets.SPN_API_KEY }}
        run: |
          if [ -z "$SPN_API_KEY" ]; then
            echo "::error::SPN_API_KEY secret not found or is empty. Please configure it in repository settings."
            exit 1
          fi

          echo "Starting spn.sh with custom arguments..."
          
          # [修正] 移除了不存在的 -v 参数
          ./spn.sh -a "$SPN_API_KEY" ${{ inputs.spn_args }} "${{ inputs.target_url }}" > spn_output.log

          echo "Script finished. Full output log:"
          cat spn_output.log

          DATA_DIR=$(grep 'Data folder:' spn_output.log | awk '{print $3}')

          if [ -z "$DATA_DIR" ]; then
            echo "::error::Could not determine the spn.sh data directory from the output."
            exit 1
          fi
          
          echo "Detected data directory: $DATA_DIR"
          echo "data_dir_path=$DATA_DIR" >> "$GITHUB_OUTPUT"

      # 提交文件的步骤（此部分无需修改）
      - name: Commit Archive Files to Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: ${{ steps.spn_run.outputs.data_dir_path }}/*
          commit_message: "chore: 归档新的SPN任务结果"
          repository: /home/runner
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
