# .github/workflows/archive-pages.yml (版本 4 - 流式输出修正版)

name: '云端归档页面 (Run spn.sh)'

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: '要归档的目标 URL'
        required: true
        type: string
      spn_args:
        description: 'spn.sh 的其他参数 (例如 -n -w 7 -o ".*")'
        required: false
        default: ''
        type: string

jobs:
  archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Setup spn.sh
        run: |
          curl -L -o spn.sh https://raw.githubusercontent.com/overcast07/wayback-machine-spn-scripts/main/spn.sh
          chmod +x spn.sh

      # 核心步骤：运行脚本 (现在支持流式输出)
      - name: Run Archive Script
        id: spn_run
        env:
          SPN_API_KEY: ${{ secrets.SPN_API_KEY }}
        run: |
          if [ -z "$SPN_API_KEY" ]; then
            echo "::error::SPN_API_KEY secret not found or is empty. Please configure it in repository settings."
            exit 1
          fi

          echo "Starting spn.sh with custom arguments. Output will stream below:"
          
          # [修正] 使用 tee 实现流式输出同时保存到文件
          ./spn.sh -a "$SPN_API_KEY" ${{ inputs.spn_args }} "${{ inputs.target_url }}" | tee spn_output.log

          echo "Script finished. Extracting data directory from log..."

          # 从保存的日志文件中提取数据目录路径
          DATA_DIR=$(grep 'Data folder:' spn_output.log | awk '{print $3}')

          if [ -z "$DATA_DIR" ]; then
            echo "::error::Could not determine the spn.sh data directory from the output. Please check the full log above."
            exit 1
          fi
          
          echo "Detected data directory: $DATA_DIR"
          echo "data_dir_path=$DATA_DIR" >> "$GITHUB_OUTPUT"

      # 提交文件的步骤（此部分无需修改）
      - name: Commit Archive Files to Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: ${{ steps.spn_run.outputs.data_dir_path }}/*
          commit_message: "chore: 归档新的SPN任务结果"
          repository: /home/runner
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
