# .github/workflows/archive-pages.yml (版本 4 - 流式输出修正版)

name: '云端归档页面 (Run spn.sh)'

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: '要归档的目标 URL'
        required: true
        type: string
      spn_args:
        description: 'spn.sh 的其他参数 (例如 -n -w 7 -o ".*")'
        required: false
        default: ''
        type: string

jobs:
  archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Setup spn.sh
        run: |
          curl -L -o spn.sh https://raw.githubusercontent.com/overcast07/wayback-machine-spn-scripts/main/spn.sh
          chmod +x spn.sh

      # 核心步骤：运行脚本 (现在支持流式输出)
      - name: Run Archive Script
        id: spn_run
        env:
          SPN_API_KEY: ${{ secrets.SPN_API_KEY }}
        run: |
          if [ -z "$SPN_API_KEY" ]; then
            echo "::error::SPN_API_KEY secret not found or is empty. Please configure it in repository settings."
            exit 1
          fi

          echo "Starting spn.sh with custom arguments. Output will stream below:"
          
          # [修正] 不再保存spn_output.log
          ./spn.sh -a "$SPN_API_KEY" ${{ inputs.spn_args }} "${{ inputs.target_url }}"

      # 步骤 4: 上传结果文件
      # 脚本运行结束后，工作环境会被销毁，所以需要将结果文件打包上传
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: spn-results
          # spn.sh 默认将文件保存在这个路径下
          path: ~/.local/share/spn-data/
          if-no-files-found: warn # 如果没有文件产生，仅警告不报错
